[build]
  command = "yarn web:build"
  publish = "packages/web/dist"
  functions = "netlify/functions"

[dev]
  command = "yarn web:dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
